set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Reloaded!"


set -g default-terminal "screen-256color"

set -g status-style bg=colour235,fg=colour255
set -g status-left-style bg=colour235,fg=colour39
set -g status-right-style bg=colour235,fg=colour39

set -g status-left "#[fg=colour39,bold] [ #S ] #[default]"

set -g status-right "#[fg=colour39] %Y-%m-%d #[fg=colour39] %H:%M #[default]"

set -g status-interval 1

set -g window-status-format "#[fg=colour245] #I: #W #[default]"

set -g window-status-current-format "#[fg=colour39,bg=colour236,bold] #I: #W #[default]"
set -g window-status-current-style bg=colour236,fg=colour39,bold

set -g window-status-activity-style bg=colour235,fg=colour39

set -g pane-border-style fg=colour239
set -g pane-active-border-style fg=colour39

bind | split-window -h
bind - split-window -v

bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D

bind -n C-M-Left resize-pane -L 5
bind -n C-M-Right resize-pane -R 5
bind -n C-M-Up resize-pane -U 5
bind -n C-M-Down resize-pane -D 5

set -g renumber-windows on

set -g terminal-overrides "xterm*:smcup@:rmcup@"

set -g message-style bg=colour39,fg=colour235

set -g mode-style bg=colour236,fg=colour39
